// Sudoku generated by generate_sudoku.js
let sudoku = [];

// This sudoku will be displayed to the player
let visibleSudoku = [];

// Cell currently selected by the player
let cellSelected = null;

// Difficulty selected by the player
let difficultySelected = Number(localStorage.getItem("difficulty")) || 30;

// Numbers entered by the player
let player = [];
for (let i = 0; i < 9; i++) {
    player.push(Array(9).fill(0));
}

// Reset all Sudoku matrices
function resetMatrices() {
    sudoku = [];
    player = [];
    visibleSudoku = [];
    // Create the 9 rows 
    for (let row = 0; row < 9; row++) {
        sudoku[row] = [];
        visibleSudoku[row] = [];
        player[row] = [];
        // Create the 9 columns 
        for (let column = 0; column < 9; column++) {
            sudoku[row][column] = 0;
            visibleSudoku[row][column] = 0;
            player[row][column] = 0;
        }
    }
}