// Sudoku generated by generate_sudoku.js
let sudoku = [];

// This sudoku will be displayed to user
let VisibleSudoku = [];

// Save the cell who user have selected when is playing 
let CellSelected = null;

// This variable save the difficulty which was selected in the last .js (select-difficulty.js)
let DifficultySelected = Number(localStorage.getItem("difficulty"));

// This create a matrix and represent the numbers entered by the player
let player = [];
for (let i = 0; i < 9; i++) {
    player.push(Array(9).fill(0));
}

// Reset all matrixes of sudoku
function MatrixesReset () {
    sudoku = [];
    player = [];
    VisibleSudoku = [];
    // Create the 9 rows 
    for (let fila = 0; fila < 9; fila++) {
        // Create an empty row in sudoku and player 
        sudoku[fila] = [];
        player[fila] = [];
        // Create the 9 columns for each row.
        for (let columna = 0; columna < 9; columna++) {
            sudoku[fila][columna] = 0;
            player[fila][columna] = 0;
        }
    }
}